services:
  web:
    build: ./front
    container_name: vite-frontend
    ports:
      - "3000:80"
    depends_on:
      - api

  api:
    build: ./api
    container_name: express-api
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/twygodb
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: twygo-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twygodb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
