FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma
COPY tsconfig.json ./
COPY src ./src
COPY entrypoint.sh /entrypoint.sh
RUN apk add --no-cache dos2unix && dos2unix /entrypoint.sh && chmod +x /entrypoint.sh

RUN chmod +x /entrypoint.sh

RUN npx prisma generate

RUN npm run build

COPY videos ./dist/videos

ENTRYPOINT ["/entrypoint.sh"]

CMD ["npm", "run", "start"]
