FROM node:20-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy remaining files
COPY prisma ./prisma
COPY tsconfig.json ./
COPY src ./src
COPY videos ./dist/videos

# Generate Prisma client
RUN npx prisma generate

# Build the TypeScript project
RUN npm run build

# Start application
CMD ["npm", "run", "start"]
